# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
# CodeRabbit Configuration for Laravel DDD Foundation Package
# Documentation: https://docs.coderabbit.ai/

language: en-US

early_access: false

reviews:
  # Only critical issues, no nitpicks or style suggestions
  profile: chill

  # Approve once comments resolved
  request_changes_workflow: true

  # Summary & walkthrough settings
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  collapse_walkthrough: false
  changed_files_summary: true
  sequence_diagrams: false
  poem: false
  review_status: true

  # Auto-review settings
  auto_review:
    enabled: true
    drafts: true
    base_branches:
      - main
      - develop

  # File patterns to exclude from review
  path_filters:
    - "!vendor/**"
    - "!node_modules/**"
    - "!*.lock"
    - "!build/**"
    - "!coverage/**"
    - "!.phpunit.cache/**"
    - "!_ide_helper*.php"
    - "!.phpstorm.meta.php"

  # Path-based review instructions
  path_instructions:
    - path: "src/Domain/**"
      instructions: |
        This is the Domain Layer. Review for:
        - Pure PHP without framework dependencies (Laravel helpers like collect(), str() are acceptable)
        - No direct database or infrastructure concerns

        IMMUTABILITY IS CRITICAL - Flag violations as blocking:
        - All Value Objects MUST use `readonly` properties
        - Value Objects MUST NOT have setter methods
        - Methods that "change" state MUST return new instances (e.g., `return new self(...)` or `return self::fromArray(...)`)
        - Entities MUST use `readonly` for identity properties (id)
        - Entities MUST use `CarbonImmutable` instead of `Carbon` for timestamps
        - Collections in Entities should be replaced via new instance, not mutated
        - Domain Events MUST be `readonly class`

        Valid immutable pattern:
        ```php
        public function withName(string $name): self
        {
            return new self($this->id, $name, $this->other);
        }
        ```

        Invalid mutable pattern (flag this):
        ```php
        public function setName(string $name): void
        {
            $this->name = $name; // ❌ Mutation!
        }
        ```

    - path: "src/Application/**"
      instructions: |
        This is the Application Layer. Review for:
        - Orchestration logic only, no business rules
        - Proper use of domain services and repositories
        - No direct database access (use repositories)

    - path: "src/Infrastructure/**"
      instructions: |
        This is the Infrastructure Layer. Review for:
        - Proper implementation of domain contracts/interfaces
        - Eloquent models should extend the base Model class
        - Mappers must correctly translate between Entity and Model
        - Repository implementations must handle transactions and events

    - path: "tests/**"
      instructions: |
        Review tests for:
        - Using Pest PHP testing framework
        - Proper test isolation
        - Meaningful test descriptions

  # Auto-labeling configuration
  labeling_instructions:
    - label: "domain"
      instructions: "Apply when PR contains changes to src/Domain/**"
    - label: "infrastructure"
      instructions: "Apply when PR contains changes to src/Infrastructure/**"
    - label: "application"
      instructions: "Apply when PR contains changes to src/Application/**"
    - label: "tests"
      instructions: "Apply when PR contains changes to tests/**"
    - label: "documentation"
      instructions: "Apply when PR contains changes to *.md files or docs/**"
    - label: "dependencies"
      instructions: "Apply when PR contains changes to composer.json"
    - label: "ci"
      instructions: "Apply when PR contains changes to .github/**"
    - label: "breaking-change"
      instructions: "Apply when PR introduces breaking changes to public APIs, method signatures, or contracts"

  auto_apply_labels: true
  suggested_labels: true

  # Pre-merge checks for title validation
  pre_merge_checks:
    title:
      mode: warning
      requirements: |
        PR title must follow Conventional Commits format: type(scope)?: description
        Valid types: feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert
        Example: feat(value-objects): add Money value object

chat:
  auto_reply: true

knowledge_base:
  opt_out: false
  learnings:
    scope: auto
  issues:
    scope: auto
  pull_requests:
    scope: auto